### ISSUE TITLE
Request token always throws "invalid scopes"

### ISSUE THREAD

**Issue by vaindil** [swiftyspiffy/twitch-token-generator#1]
I'm trying to use the request token feature, but no matter what I do I always get "invalid scopes" thrown when I click "Generate Link" in the modal. This happens regardless of which scopes I choose, I couldn't find any combination that actually worked. No console errors are thrown when the alert is thrown, but my console is full of errors like this, pointing to `TwitchController.js:12`:

```
Uncaught TypeError: Cannot read property 'getAttribute' of null
    at BasicController.isPlaying (TwitchController.js:12)
    at BasicController.getState (BasicController.js:226)
    at window.sendState (content.js:98)
    at MutationObserver.BasicController.stateChangeObserver.WebKitMutationObserver (BasicController.js:74)
```

**Comment by swiftyspiffy** [comment]
I’ll look into the issue here in a few hours.

**Comment by vaindil** [comment]
Reinstalled Windows recently and Fiddler was being stupid, finally got it working. -_- The request being sent is:

```
POST /request/create.php
scopes=clips%3Aedit%2Bchat_login&my_name=vaindil&my_email=me%40example.com
```

**Comment by vaindil** [comment]
Ah, looks like the Helix scopes aren't accepted in `create.php`, is that intended?

**Comment by swiftyspiffy** [comment]
Alright, pushed some code to the server. Try again.

**Comment by vaindil** [comment]
Perfect, it works now. Thank you!

**Comment by swiftyspiffy** [comment]
Awesome!
