### ISSUE TITLE
 provide own ClientID?

### ISSUE THREAD

**Issue by mmuziek** [swiftyspiffy/twitch-token-generator#12]
Hey i wonder.
i wanna use this system but how can i provide my own ClientID and Secret when using the API?
currently it uses a ClientID from the generator itself. but if it changes it completely breaks the system at my end point?

how can i do that thanks in advance!

**Comment by d-fischer** [comment]
You should write your own OAuth flow instead.

Passing your own client secret to anyone or anything out of your own control is a breach of the Twitch Developer Agreement.

**Comment by mmuziek** [comment]
I didnt say that
I made a program that is basically a Bot that monitors and listens to events on channels.
the Client id is shared on the same program and listens for the channels that are in since the change of twitch that it needs a client id with the token the clientID must be the same for everyone otherwise the tokens do not work and i have to create a seperate bot for each user in the same program causing issues with performance.
to counteract this allowing the api to get a ClientID (which is public from the docs of Twitch) so it then uses the ClientID to generate the unique token.
The ClientID isnt shared across different people it only is used to generate tokens for the different channels. for pubsub

**Comment by d-fischer** [comment]
You said that you want to use a custom client ID and secret with TwitchTokenGenerator. That already constitutes "sharing".

**Comment by mmuziek** [comment]
ur misunderstanding my app allows each streamer to get their own token
However because its 1 bot doing the actions it can only use 1 ClientID at the same time to sub using pubsub.
or you must know a way to get tokens with 1 clientID that isnt provided.
but i do not know if the ID from the tokengen changes because if it does it basically gets stuck

**Comment by swiftyspiffy** [comment]
While this functionality does now exist, you should avoid using this functionality for any prod integrations. This tool is strictly for testing, mvping, etc and should not be used for *any* prod stuff.
