### ISSUE TITLE
Can't refresh tokens due to Cloudflare??

### ISSUE THREAD

**Issue by SierraJC** [swiftyspiffy/twitch-token-generator#14]
When requesting `https://twitchtokengenerator.com/api/refresh/[REDACTED]` my bot is being hit with a Cloudflare challenge... is this intended? My chat bot can't automatically refresh tokens because of it

**Comment by swiftyspiffy** [comment]
Hi. Ya the server was getting absolutely slammed. I've sent an email to git@sierrac.dev .
