### ISSUE TITLE
Unable to refresh token (StatusCode: 500, ReasonPhrase: 'Internal Server Error')

### ISSUE THREAD

**Issue by SirBitesalot** [swiftyspiffy/twitch-token-generator#17]
seems like something broke

**Comment by SirBitesalot** [comment]
I am still getting this error seems like it is not a temporary one.

**Comment by Ravendwyr** [comment]
OAuth tokens created by this are only valid for four hours and the option to use the refresh token doesn't work. Help!

**Comment by swiftyspiffy** [comment]
Apologies have been quite busy. The refresh API (and onside option) should be working again. Code needed slight changes for a change Twitch made.

I've also disabled cloudflare for now. If the site gets obliterated with requests, I'll need to add it back again. Closing this for now. Feel free to reopen if needed.
