### ISSUE TITLE
Helix scopes seem to be ignored

### ISSUE THREAD

**Issue by bcjordan** [swiftyspiffy/twitch-token-generator#2]
I'm finding that when I toggle only Helix scopes, it shows the error:

> You need to select at least one scope to generate a token.

And when mixing v5 and Helix permissions, only the v5 permissions seem to get set.

(Caveat is it's entirely possible I'm mis-understanding the UI!)

**Comment by swiftyspiffy** [comment]
Yup, good catch. Fixing now.

**Comment by swiftyspiffy** [comment]
Hmm, it seems there was a small bug in the js along with Twitch appears to have changed one of their Helix scopes.

Should be fixed now though, go ahead and give it a go and let me know if you encounter a problem.
