### ISSUE TITLE
Missing whispers:read and whispers:edit scopes

### ISSUE THREAD

**Issue by sogehige** [swiftyspiffy/twitch-token-generator#3]
As chat_login is [deprecated](https://dev.twitch.tv/docs/release-notes/), twitch introduced whispers scopes foc chat and pubsub

https://dev.twitch.tv/docs/authentication/

Scope Name | Type of Access
channel:moderate | Perform moderation actions in a channel.
chat:edit | Send live stream chat and rooms messages.
chat:read | View live stream chat and rooms messages.
whispers:read | View your whisper messages.
whispers:edit | Send whisper messages.

**Comment by swiftyspiffy** [comment]
Hey! Thanks for bringing this to my attention. I've added the two scope values under Helix. Will consider creating a new section for `Chat and Pubsub` like they have in the docs.
