### ISSUE TITLE
Is anyone else getting the error; "Client ID and OAuth token do not match"?

### ISSUE THREAD

**Issue by liquidvisual** [swiftyspiffy/twitch-token-generator#5]
I just started getting this out of nowhere. No tokens are working anymore, my client ID hasn't changed. Anyone else experiencing this? :/

Btw, love the app - it's been a real help - thanks for your work. <3

**Comment by pnkllr** [comment]
I too have now started getting this. Using the client ID provided on the site.

**Comment by liquidvisual** [comment]
@pnkllr The client ID is working for me again now. I'm not sure why it wasn't before.
