### ISSUE TITLE
[Fix] Typo in latest scopes

### ISSUE THREAD

**Issue by iProdigy** [swiftyspiffy/twitch-token-generator#7]
### Context
Twitch newly documented `channel:manage:extension` and `channel:manage:brodcast` as possible scopes & they have been implemented as documented into the website.

### Issue
Trying to request these scopes will fail with an error 400: invalid scope requested.

### Solution
Fix the typos
* `channel:manage:extension` should be `channel:manage:extensions` (missing the final "s")
* `channel:manage:brodcast` should be `channel:manage:broadcast` (missing an "a" in broadcast)

**Comment by swiftyspiffy** [comment]
Checking.

**Comment by swiftyspiffy** [comment]
Fixed. Thanks for bringing attention to this!
