### ISSUE TITLE
Error 403 Forbidden

### ISSUE THREAD

**Issue by Deanosim** [swiftyspiffy/twitch-token-generator#9]
When trying to setup my bot using Sogebot if I try to go to https://twitchtokengenerator.com/quick/jLbq7v1pzF or https://twitchtokengenerator.com or any version I get 403 forbidden, I don't understand why because this is my dedicated home internet ip address, is it possible the IP was blacklisted before I got it from my ISP? Is there anything that can be done about this? Or do I need to contact my ISP and get a different IP. Because If I use a VPN I can access the token generator and get the tokens for my bot just fine.

**Comment by swiftyspiffy** [comment]
Can you message me your username/userid or IP associated with the calls you're making? It's possible it was automatically done. You can message me on [twitter](https://twitter.com/swiftyspiffy) or discord ( `swiftyspiffy#0001` ).

**Comment by swiftyspiffy** [comment]
Closing this as it was solved over DMs.
